server:
  port: 8088
security:
  basic:
    enable: false
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/songs
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update