server:
  port: 8088
security:
  basic:
    enable: false
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update